### ISSUE TITLE
오탈자가 보여서 올립니다.

### ISSUE THREAD

**Issue by tommy-h** [innovationacademy-kr/FAQ#4]
<h1>이노베이션 아카데미란?</h1>

<ul><li>

이노베이션 아카데미는 창의성(Creativity), 비판적 사고(Critical Thinking), 도전정신(Challenge), 융합(Convergence), 공감과 협업(Collaboration)의 5C 역량을 가진 인재 양성을 목표로 합니다. 모든 사람은 자신만의 특별한 영역에 창의성을 가지고 있기 때문에, 다른 4개의 역량을 키워 이미 가지고 있던 창의성으로 세상을 바꿀 수 있는 *혁신적 인재 양성* **('혁신적 인재를' 혹은 '혁신적인 인재를' 로 수정 필요)** 하고자 합니다.

</li></ul>

<h3>커리큘럼은 어떻게 구성되어 있나요?</h3>

<ul><li>

이노베이션 아카데미는 특정 문제를 해결하는 스킬 혹은 도구를 사용하는 방법을 가르쳐주지 않습니다. 모든 것을 스스로, 동료와 함께 배우고, 주어진 도구들을 이용하여 문제를 해결하면서 역량을 *키워나가데* **('키워나가게' 로 수정 필요)** 됩니다.

</li></ul>

<h3>동료간 학습을 통한 교육방식이 무슨 뜻인가요?</h3>

<ul><li>

비판적 사고, 협동심 및 의사소통 극대화를 기대하는 교육방식으로서 동료간 학습은, 교수의 수업을 통해 지식을 전달받는 방식이 아닌 교육생 서로가 협력적으로 *학습하고 및 서로를 평가하면서* **('학습하고 서로를 평가하면서' 로 수정 필요)** 성장하는 교육방식입니다. 

</li></ul>

**Comment by minsuklee** [comment]
처리되었습니다, 고맙습니다.
