### ISSUE TITLE
질문이용

### ISSUE THREAD

**Issue by rosejam** [innovationacademy-kr/FAQ#7]
1. '42 SEOUL가 교육생의 역량 증진에 도움이 안되는 경우, 본인의 커리어를 위해서 그만 두게 할 수도 있습니다. '라는게 학습이 부진하면 퇴출된다는 뜻인가요?
2. 장학금은 한달에 약 100만원이라고 들었는데 아직 미정이지만 비슷한 범위인가요?
3. '7~10 레벨을 통과한 교육생은 인턴십을 해야하며, 이 인턴십은 교육의 일부로 간주됩니다.'라는 말은 계속 진행하려면 인턴십이 필수라는 말인가요?
4. 컴퓨터는 데스크탑만 지원되나요?

**Comment by minsuklee** [comment]
1. 맞습니다. 학습 부진보다는 학습 불성실이 더 맞는 표현인듯 하지만요.
2. 한달에 100만원인데, 조건도 조금 있고, 세금 관련한 공제도 있어 100만원 보다는 조금 적다고 보시면 됩니다.
3. 딱 이때 이 곳에 가야한다고 지정되지는 않겠지만. 인턴십은 하셔야 합니다.
4. 옙. 학습 공간에는 iMac이 설치되고, 만일을 대비해서 노트북이 조금 준비됩니다.

**Comment by rosejam** [comment]
답변 감사합니다 :)
