### ISSUE TITLE
FAQ에 대한 질문

### ISSUE THREAD

**Issue by sebuls** [innovationacademy-kr/FAQ#8]
FAQ 중에서
첫 단계인 한 달 집중학습 기간은 주중 주말 휴일과 상관없이 매일 등교를 해야합니다. 반드시 출석해야 하는 시험도 있지만, 전체 교육생들이 모여 동료 학습을 하기 위함입니다.
월화수목금토일 다 등교라는 건가요?
군대로 말하면 훈련소 같은 개념?
궁금해서 질문 하나 던져 봅니다.

**Comment by minsuklee** [comment]
무조건은 아닙니다. 질문을 보고 본문에 '거의'를 붙였습니다. 워낙 해야할 과제와 프로젝트가 많은데 혼자서 할 수가 없고, 동료들과 같이 해야하면 과제, 프로젝트 제출을 현장에서만 할 수 있기 때문에 매일 나올 수 밖에 없고, 토요일엔 물리적인 시험을 봅니다.
