### ISSUE TITLE
FAQ 페이지에서의 마크다운 파싱 문제

### ISSUE THREAD

**Issue by PlavorSeol** [innovationacademy-kr/FAQ#9]
42 Seoul [FAQ 페이지](https://42seoul.kr/faq)가 이 리포지토리의 [README.md](https://github.com/innovationacademy-kr/FAQ/blob/master/README.md) 파일을 로드하는 것으로 보이는데, [FAQ 페이지](https://42seoul.kr/faq)에서 "42 SEOUL(42 서울)이란?" 섹션을 보시면 `[개포디지털혁신파크](http://naver.me/I5tKCgdx)` 부분이 그대로 출력되는 것을 볼 수 있습니다.
[FAQ 페이지](https://42seoul.kr/faq)에서 마크다운 문법을 제대로 파싱하지 못하는 것으로 보이는데, 이를 정상적으로 파싱하도록 해당 페이지를 수정하시거나 [README.md](https://github.com/innovationacademy-kr/FAQ/blob/master/README.md) 파일에서 해당 부분의 링크를 제거해야 할 것 같습니다.
[README.md](https://github.com/innovationacademy-kr/FAQ/blob/master/README.md) 파일에서 링크를 제거할 경우 URL 없이 `개포디지털혁신파크`라고만 적어 놓거나 괄호를 사용해서 `개포디지털혁신파크 (http://naver.me/I5tKCgdx)`와 같은 방법으로 표기하는 것이 좋다고 생각합니다.

**Comment by minsuklee** [comment]
예 url을 제거했습니다.
